version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     # For local debugging of Main
     # - ADVERTISED_HOST_NAME=192.168.1.3
  order-db:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=orderdb
  shipment-db:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  shipment-db-quarkus:
    image: mariadb/server
    ports:
     - "33306:3306"
    healthcheck:
      test: "/usr/bin/mysql -h shipment-db-quarkus --user=mariadbuser --password=mariadbpw --execute \"SELECT 1;\" shipmentdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
     - MARIADB_USER=mariadbuser
     - MARIADB_PASSWORD=mariadbpw
     - MARIADB_DATABASE=shipmentdb
     - MARIADB_RANDOM_ROOT_PASSWORD=true
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - order-db
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
     - KAFKA_DEBUG=true
     - DEBUG_SUSPEND_FLAG=n
  order-service:
    image: debezium-examples/outbox-order-service:latest
    build:
      context: order-service
    ports:
     - 8080:8080
     - 8787:8787
     - 9990:9990
    links:
     - kafka
     - order-db
     - schema-registry
    environment:
     - SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - 5005:5005
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
     - 8181:8181
     - 8081:8081
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    links:
     - zookeeper
